apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: client
  name: client
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 3000
  selector:
    io.kompose.service: client
